# Specify the operating system that we want Travis to use for our build
os: osx

name: "iOS Unit Tests"
language: swift
osx_image: xcode11.3
xcode_project: WWCode_Tokyo_iOS.xcodeproj
xcode_scheme: WWCode_Tokyo_iOS
xcode_destination: platform=iOS Simulator,OS=latest,name=iPhone 11
install:
  - cd ios
  - make bootstrap
