# Specify the operating system that we want Travis to use for our build
os: osx

# Cache iOS project dependencies to speed up builds by only building new dependencies
cache:
  directories:
    # iOS Cache
    - ./ios/Carthage
    # Gradle Cache
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

matrix:
  include:
    - name: "iOS Unit Tests"
      language: swift
      osx_image: xcode11.3
      xcode_project: WWCode_Tokyo_iOS.xcodeproj
      xcode_scheme: WWCode_Tokyo_iOS
      xcode_destination: platform=iOS Simulator,OS=latest,name=iPhone 11
      install:
        - cd ios
        - make bootstrap

    - name: "Spring Server Unit Tests"
      language: java
      jdk: openjdk8
      install:
        - cd server
        - make test
#      deploy:
#        provider: cloudfoundry
#        username: $CF_USERNAME
#        password:
#          secure: $CF_SECURED_PASSWORD
#        api: $CF_URL
#        organization: $CF_ORG
#        space: $CF_SPACE
